resources:
- name: repo
  type: git
  source:
    uri: https://github.com/Qizly/concourse-test
    branch: main
    username: shubo@mac.com
    password: amu9ona3#


jobs:
- name: hello-world-job
  plan:
  - get: repo
    trigger: true
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: gitea/gitea
      inputs:
      - name: repo
      outputs:
      - name: repo
      params:
        EMAIL: shubo@mac.com
        GIT_AUTHOR_NAME: Yong Lee
      run:
        path: sh
        args:
        - cx
        - |
          cd repo
          date +%Y-%m-%d > todays-date
          git add ./todays-date
          git config --global user.email $EMAIL
          git config --global user.name $GIT_AUTHOR_NAME
          git commit -m "Update todays date"
  - put: repo
    params:
      repository: repo